import React, { useState, useEffect } from 'react';
import {
  StructuredUserContext,
  ControlledActionLog,
} from '../types/academic';
import {
  Cpu,
  Code,
  ShieldCheck,
  Play,
  FileText,
  Layers,
  Sparkles,
  CheckCircle2,
  AlertCircle,
  Copy,
  Check,
  RefreshCw,
  Terminal,
  Database,
  ArrowRight,
} from 'lucide-react';
import { api, ToolsResponse, RecommendationResponse } from '../services/apiClient';

interface AiArchitectureInspectorProps {
  context: StructuredUserContext;
  promptDigest: string;
  onContextChanged: () => void;
}

export const AiArchitectureInspector: React.FC<AiArchitectureInspectorProps> = ({
  context,
  promptDigest,
  onContextChanged,
}) => {
  const [activeSubTab, setActiveSubTab] = useState<'context' | 'tools' | 'sandbox' | 'advisor' | 'audit'>('context');
  const [contextFilter, setContextFilter] = useState<'all' | 'tasks' | 'goals' | 'exams' | 'deadlines' | 'schedule' | 'tests' | 'history' | 'performance' | 'preferences'>('all');
  const [toolsData, setToolsData] = useState<ToolsResponse | null>(null);
  const [auditLogs, setAuditLogs] = useState<ControlledActionLog[]>([]);
  const [advisorRec, setAdvisorRec] = useState<RecommendationResponse['recommendation'] | null>(null);

  // Sandbox state
  const [selectedAction, setSelectedAction] = useState('create_study_task');
  const [sandboxParams, setSandboxParams] = useState<Record<string, any>>({
    title: 'Review Improper Integrals & Comparison Test',
    subject: 'Calculus II',
    dueDate: new Date(Date.now() + 86400000 * 3).toISOString().split('T')[0],
    priority: 'high',
    estimatedMinutes: 60,
    description: 'Generated by AI Advisor recommendation following quiz gap analysis.',
    tags: ['ai-recommended', 'remediation'],
  });
  const [isDryRun, setIsDryRun] = useState(false);
  const [sandboxResult, setSandboxResult] = useState<any>(null);
  const [isExecuting, setIsExecuting] = useState(false);
  const [copiedJson, setCopiedJson] = useState(false);

  useEffect(() => {
    loadTools();
    loadAuditLogs();
  }, []);

  const loadTools = async () => {
    try {
      const data = await api.getTools();
      setToolsData(data);
    } catch (err) {
      console.error(err);
    }
  };

  const loadAuditLogs = async () => {
    try {
      const data = await api.getAuditLogs();
      setAuditLogs(data.logs);
    } catch (err) {
      console.error(err);
    }
  };

  const handleSimulateAdvisor = async () => {
    try {
      const res = await api.getAdvisorRecommendation();
      setAdvisorRec(res.recommendation);
      setActiveSubTab('advisor');
    } catch (err) {
      console.error(err);
    }
  };

  const handleExecuteSandboxAction = async () => {
    setIsExecuting(true);
    try {
      const res = await api.executeControlledAction(selectedAction, sandboxParams, isDryRun);
      setSandboxResult(res);
      await loadAuditLogs();
      if (!isDryRun && res.success) {
        onContextChanged();
      }
    } catch (err) {
      console.error(err);
      setSandboxResult({ success: false, message: 'Execution request failed' });
    } finally {
      setIsExecuting(false);
    }
  };

  const handleExecuteSuggestedAction = async (action: any) => {
    setIsExecuting(true);
    try {
      const res = await api.executeControlledAction(action.actionName, action.parameters, false);
      setSandboxResult(res);
      await loadAuditLogs();
      onContextChanged();
    } catch (err) {
      console.error(err);
    } finally {
      setIsExecuting(false);
    }
  };

  const handleActionSelectChange = (name: string) => {
    setSelectedAction(name);
    setSandboxResult(null);

    // Pre-populate sensible sample parameters for testing
    switch (name) {
      case 'create_study_task':
        setSandboxParams({
          title: 'Review Organic Chemistry Reaction Mechanisms',
          subject: 'Organic Chemistry',
          dueDate: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
          priority: 'urgent',
          estimatedMinutes: 90,
          description: 'Focus on carbocation stability and SN1/SN2 distinction.',
          tags: ['ai-task', 'exam-prep'],
        });
        break;
      case 'reschedule_task':
        const firstTask = context.tasks[0];
        setSandboxParams({
          taskId: firstTask ? firstTask.id : 'task-1',
          newDueDate: new Date(Date.now() + 86400000 * 4).toISOString().split('T')[0],
          newPriority: 'medium',
          reason: 'Balancing workload around Wednesday chemistry lab.',
        });
        break;
      case 'create_academic_goal':
        setSandboxParams({
          title: 'Master All Organic Chemistry Nomenclature & Mechanisms',
          category: 'exam_prep',
          subject: 'Organic Chemistry',
          targetDate: '2026-10-15',
          targetValue: 100,
          unit: '% syllabus mastered',
          initialMilestones: ['Alkenes & Alkynes', 'Substitution reactions', 'Spectroscopy'],
        });
        break;
      case 'update_goal_progress':
        const firstGoal = context.goals[0];
        setSandboxParams({
          goalId: firstGoal ? firstGoal.id : 'goal-1',
          newCurrentValue: firstGoal ? Math.min(firstGoal.targetValue, firstGoal.currentValue + 10) : 75,
          completedMilestoneIndex: 1,
          progressNotes: 'Completed additional practice test successfully.',
        });
        break;
      case 'reorganize_study_schedule':
        setSandboxParams({
          focusSubject: 'Calculus II',
          rationale: 'Exam in 17 days, recent quiz score 80% requires focus.',
        });
        break;
      case 'log_study_session':
        setSandboxParams({
          subject: 'Data Structures',
          durationMinutes: 45,
          focusScore: 9,
          topicsCovered: ['B-Trees', 'Disk-based indexing'],
          notes: 'Completed practice exercises with high focus.',
        });
        break;
      case 'record_daily_test_result':
        setSandboxParams({
          subject: 'Modern History',
          title: 'European Alliances Flash Quiz',
          score: 10,
          totalQuestions: 10,
          timeSpentMinutes: 10,
          weakTopics: [],
          strengths: ['Triple Entente', 'Bismarck diplomatic system'],
          reflections: '100% accuracy on review quiz.',
        });
        break;
      case 'update_study_preferences':
        setSandboxParams({
          studyPace: 'intensive',
          targetDailyStudyHours: 4.5,
          weakSubjects: ['Organic Chemistry', 'Calculus II'],
          advisorPersonality: 'analytical',
        });
        break;
      default:
        setSandboxParams({});
    }
  };

  // Filter context for JSON viewer
  const getFilteredContext = () => {
    if (contextFilter === 'all') return context;
    if (contextFilter === 'tasks') return { tasks: context.tasks };
    if (contextFilter === 'goals') return { goals: context.goals };
    if (contextFilter === 'exams') return { exams: context.exams };
    if (contextFilter === 'deadlines') return { upcomingDeadlines: context.upcomingDeadlines };
    if (contextFilter === 'schedule') return { schoolSchedule: context.schoolSchedule };
    if (contextFilter === 'tests') return { dailyTests: context.dailyTests };
    if (contextFilter === 'history') return { studyHistory: context.studyHistory };
    if (contextFilter === 'performance') return { testPerformance: context.testPerformance };
    if (contextFilter === 'preferences') return { userPreferences: context.userPreferences };
    return context;
  };

  const copyContextJson = () => {
    navigator.clipboard.writeText(JSON.stringify(context, null, 2));
    setCopiedJson(true);
    setTimeout(() => setCopiedJson(false), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Top Architectural Architecture Overview */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 text-white shadow-sm space-y-4">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 bg-indigo-600 rounded-lg text-white shadow-xs">
              <Cpu className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <h2 className="text-lg font-bold">Personal Study Advisor: Decoupled AI Architecture</h2>
                <span className="px-2 py-0.5 text-xs font-semibold rounded bg-emerald-500/20 text-emerald-300 border border-emerald-500/40">
                  Ready for Gemini Hookup
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Architectural separation of UI Presentation, Data Persistence (DAL), and AI Controlled Actions.
              </p>
            </div>
          </div>

          <button
            id="btn-run-advisor-sim"
            onClick={handleSimulateAdvisor}
            className="flex items-center space-x-2 px-4 py-2 rounded-lg text-xs font-semibold bg-indigo-600 hover:bg-indigo-500 text-white transition shadow-sm self-start md:self-auto"
          >
            <Sparkles className="w-4 h-4" />
            <span>Generate Advisor Diagnosis</span>
          </button>
        </div>

        {/* Visual Architectural Diagram */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3 pt-2 text-xs">
          <div className="bg-slate-800/80 border border-slate-700/80 rounded-lg p-3 space-y-1.5">
            <div className="flex items-center space-x-1.5 text-indigo-400 font-semibold">
              <Layers className="w-4 h-4" />
              <span>1. Client UI & REST API</span>
            </div>
            <p className="text-slate-400 leading-relaxed">
              React SPA displaying tasks, goals, exams, schedule, and quiz analytics. Interacts strictly via <code>/api/*</code>.
            </p>
          </div>

          <div className="bg-indigo-950/40 border border-indigo-800/60 rounded-lg p-3 space-y-1.5">
            <div className="flex items-center space-x-1.5 text-indigo-300 font-semibold">
              <ShieldCheck className="w-4 h-4" />
              <span>2. Controlled Action Registry</span>
            </div>
            <p className="text-indigo-200/80 leading-relaxed">
              Server-authoritative boundary with schema checks, guardrails, and audit logging. The AI only modifies data via declared actions.
            </p>
          </div>

          <div className="bg-emerald-950/40 border border-emerald-800/60 rounded-lg p-3 space-y-1.5">
            <div className="flex items-center space-x-1.5 text-emerald-300 font-semibold">
              <Database className="w-4 h-4" />
              <span>3. Isolated Data Layer (DAL)</span>
            </div>
            <p className="text-emerald-200/80 leading-relaxed">
              Independent data store holding structured models. AI logic does not execute raw SQL/mutations directly.
            </p>
          </div>
        </div>
      </div>

      {/* Subtabs Navigation */}
      <div className="border-b border-slate-200 dark:border-slate-700">
        <nav className="flex space-x-4">
          <button
            onClick={() => setActiveSubTab('context')}
            className={`pb-3 text-sm font-medium border-b-2 flex items-center space-x-1.5 transition ${
              activeSubTab === 'context'
                ? 'border-indigo-600 text-indigo-600 dark:text-indigo-400 font-bold'
                : 'border-transparent text-slate-500 hover:text-slate-700 dark:hover:text-slate-300'
            }`}
          >
            <FileText className="w-4 h-4" />
            <span>Structured Context Explorer</span>
          </button>

          <button
            onClick={() => setActiveSubTab('tools')}
            className={`pb-3 text-sm font-medium border-b-2 flex items-center space-x-1.5 transition ${
              activeSubTab === 'tools'
                ? 'border-indigo-600 text-indigo-600 dark:text-indigo-400 font-bold'
                : 'border-transparent text-slate-500 hover:text-slate-700 dark:hover:text-slate-300'
            }`}
          >
            <Code className="w-4 h-4" />
            <span>Gemini Function Declarations ({toolsData?.tools.length || 8})</span>
          </button>

          <button
            onClick={() => setActiveSubTab('sandbox')}
            className={`pb-3 text-sm font-medium border-b-2 flex items-center space-x-1.5 transition ${
              activeSubTab === 'sandbox'
                ? 'border-indigo-600 text-indigo-600 dark:text-indigo-400 font-bold'
                : 'border-transparent text-slate-500 hover:text-slate-700 dark:hover:text-slate-300'
            }`}
          >
            <Play className="w-4 h-4" />
            <span>Controlled Actions Sandbox</span>
          </button>

          <button
            onClick={() => setActiveSubTab('advisor')}
            className={`pb-3 text-sm font-medium border-b-2 flex items-center space-x-1.5 transition ${
              activeSubTab === 'advisor'
                ? 'border-indigo-600 text-indigo-600 dark:text-indigo-400 font-bold'
                : 'border-transparent text-slate-500 hover:text-slate-700 dark:hover:text-slate-300'
            }`}
          >
            <Sparkles className="w-4 h-4" />
            <span>Advisory Diagnostic Preview</span>
          </button>

          <button
            onClick={() => setActiveSubTab('audit')}
            className={`pb-3 text-sm font-medium border-b-2 flex items-center space-x-1.5 transition ${
              activeSubTab === 'audit'
                ? 'border-indigo-600 text-indigo-600 dark:text-indigo-400 font-bold'
                : 'border-transparent text-slate-500 hover:text-slate-700 dark:hover:text-slate-300'
            }`}
          >
            <ShieldCheck className="w-4 h-4" />
            <span>Action Audit Trail ({auditLogs.length})</span>
          </button>
        </nav>
      </div>

      {/* Subtab 1: Structured Context Explorer */}
      {activeSubTab === 'context' && (
        <div className="space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-white dark:bg-slate-800 p-4 rounded-xl border border-slate-200 dark:border-slate-700">
            <div>
              <h3 className="font-bold text-sm text-slate-900 dark:text-white">
                Live AI Context Payload
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                The exact, strongly-typed JSON structure delivered to Gemini to inform personalized study guidance.
              </p>
            </div>

            <div className="flex items-center space-x-2">
              <select
                value={contextFilter}
                onChange={(e) => setContextFilter(e.target.value as any)}
                className="text-xs px-2.5 py-1.5 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg text-slate-800 dark:text-slate-200"
              >
                <option value="all">Full Context (All 9 Domains)</option>
                <option value="tasks">1. Tasks</option>
                <option value="goals">2. Goals</option>
                <option value="exams">3. Exams</option>
                <option value="deadlines">4. Deadlines</option>
                <option value="schedule">5. School Schedule</option>
                <option value="tests">6. Daily Tests</option>
                <option value="history">7. Study History</option>
                <option value="performance">8. Test Performance</option>
                <option value="preferences">9. User Preferences</option>
              </select>

              <button
                onClick={copyContextJson}
                className="flex items-center space-x-1 text-xs px-3 py-1.5 rounded-lg border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 transition"
              >
                {copiedJson ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedJson ? 'Copied' : 'Copy JSON'}</span>
              </button>
            </div>
          </div>

          {/* Prompt Digest Preview Accordion */}
          <div className="bg-slate-900 rounded-xl border border-slate-800 p-4 text-xs font-mono text-slate-300">
            <div className="flex items-center justify-between pb-2 mb-2 border-b border-slate-800">
              <span className="text-indigo-400 font-semibold uppercase tracking-wider">
                Prompt-Optimized Digest (System Instruction Format)
              </span>
              <span className="text-slate-500">~450 tokens</span>
            </div>
            <pre className="whitespace-pre-wrap leading-relaxed max-h-48 overflow-y-auto text-slate-300 scrollbar-thin">
              {promptDigest}
            </pre>
          </div>

          {/* Raw JSON Tree */}
          <div className="bg-slate-950 rounded-xl border border-slate-800 p-4 text-xs font-mono overflow-x-auto max-h-96 scrollbar-thin">
            <pre className="text-emerald-400">
              {JSON.stringify(getFilteredContext(), null, 2)}
            </pre>
          </div>
        </div>
      )}

      {/* Subtab 2: Gemini Function Declarations */}
      {activeSubTab === 'tools' && (
        <div className="space-y-4">
          <div className="bg-white dark:bg-slate-800 p-4 rounded-xl border border-slate-200 dark:border-slate-700">
            <h3 className="font-bold text-sm text-slate-900 dark:text-white">
              Registered Gemini Function Calling Schemas
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
              Formatted according to <code>@google/genai</code> specifications. When the Gemini SDK is enabled, pass these tool declarations directly into the model configuration.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {(toolsData?.tools || []).map((tool: any) => (
              <div
                key={tool.name}
                className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 p-4 shadow-xs space-y-2"
              >
                <div className="flex items-center justify-between">
                  <span className="font-mono text-xs font-bold text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-950 px-2 py-0.5 rounded border border-indigo-200 dark:border-indigo-800">
                    {tool.name}
                  </span>
                  <span className="text-xs text-slate-400">
                    {tool.parameters.required ? `${tool.parameters.required.length} required` : '0 required'}
                  </span>
                </div>
                <p className="text-xs text-slate-600 dark:text-slate-300">
                  {tool.description}
                </p>

                <div className="pt-2 border-t border-slate-100 dark:border-slate-700 space-y-1">
                  <span className="text-xs font-semibold text-slate-500 dark:text-slate-400">
                    Parameters:
                  </span>
                  <div className="space-y-1">
                    {Object.entries(tool.parameters.properties).map(([paramName, param]: [string, any]) => (
                      <div key={paramName} className="text-xs flex items-start space-x-2">
                        <span className="font-mono text-slate-800 dark:text-slate-200 font-semibold">
                          {paramName}
                          {tool.parameters.required?.includes(paramName) && (
                            <span className="text-rose-500 ml-0.5">*</span>
                          )}
                          :
                        </span>
                        <span className="text-indigo-500 font-mono text-xs">({param.type})</span>
                        <span className="text-slate-400 text-xs truncate">{param.description}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Subtab 3: Controlled Actions Sandbox */}
      {activeSubTab === 'sandbox' && (
        <div className="space-y-6">
          <div className="bg-white dark:bg-slate-800 p-4 rounded-xl border border-slate-200 dark:border-slate-700">
            <h3 className="font-bold text-sm text-slate-900 dark:text-white">
              Controlled Server Action Invocation Sandbox
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
              Simulate Gemini invoking server-side actions. Verify that parameters pass guardrail checks, mutations are strictly contained, and audit records are generated.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Action Form */}
            <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 p-5 shadow-xs space-y-4">
              <div>
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">
                  Select Action to Dispatch
                </label>
                <select
                  id="sandbox-action-select"
                  value={selectedAction}
                  onChange={(e) => handleActionSelectChange(e.target.value)}
                  className="w-full text-xs px-3 py-2 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg text-slate-900 dark:text-white font-mono"
                >
                  <option value="create_study_task">create_study_task (Schedule new study task)</option>
                  <option value="reschedule_task">reschedule_task (Adjust task due date & reason)</option>
                  <option value="create_academic_goal">create_academic_goal (Set new goal with milestones)</option>
                  <option value="update_goal_progress">update_goal_progress (Advance goal progress)</option>
                  <option value="reorganize_study_schedule">reorganize_study_schedule (Prioritize subject tasks)</option>
                  <option value="log_study_session">log_study_session (Record focus session)</option>
                  <option value="record_daily_test_result">record_daily_test_result (Save quiz metrics)</option>
                  <option value="update_study_preferences">update_study_preferences (Update study pace)</option>
                </select>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">
                  Parameters JSON (Input payload)
                </label>
                <textarea
                  id="sandbox-params-textarea"
                  rows={8}
                  value={JSON.stringify(sandboxParams, null, 2)}
                  onChange={(e) => {
                    try {
                      setSandboxParams(JSON.parse(e.target.value));
                    } catch {
                      // allow editing
                    }
                  }}
                  className="w-full text-xs font-mono p-3 bg-slate-900 text-emerald-300 border border-slate-800 rounded-lg focus:outline-hidden"
                />
              </div>

              <div className="flex items-center justify-between pt-2">
                <label className="flex items-center space-x-2 text-xs text-slate-600 dark:text-slate-300 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={isDryRun}
                    onChange={(e) => setIsDryRun(e.target.checked)}
                    className="rounded text-indigo-600 focus:ring-indigo-500"
                  />
                  <span>Dry-Run Simulation (Validate only, do not persist)</span>
                </label>

                <button
                  id="btn-execute-sandbox-action"
                  onClick={handleExecuteSandboxAction}
                  disabled={isExecuting}
                  className="flex items-center space-x-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg text-xs font-semibold transition shadow-xs"
                >
                  <Play className="w-3.5 h-3.5" />
                  <span>{isExecuting ? 'Validating...' : isDryRun ? 'Run Dry-Run' : 'Execute Action'}</span>
                </button>
              </div>
            </div>

            {/* Execution Result Box */}
            <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 p-5 shadow-xs space-y-4">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
                  Guardrail Evaluation & Response
                </span>
                {sandboxResult && (
                  <span
                    className={`text-xs px-2 py-0.5 rounded font-semibold ${
                      sandboxResult.success
                        ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300'
                        : 'bg-rose-100 text-rose-800 dark:bg-rose-950 dark:text-rose-300'
                    }`}
                  >
                    {sandboxResult.success ? 'PASSED' : 'REJECTED BY GUARDRAILS'}
                  </span>
                )}
              </div>

              {sandboxResult ? (
                <div className="space-y-3">
                  <div
                    className={`p-3 rounded-lg text-xs border ${
                      sandboxResult.success
                        ? 'bg-emerald-50 dark:bg-emerald-950/40 border-emerald-200 dark:border-emerald-800 text-emerald-800 dark:text-emerald-200'
                        : 'bg-rose-50 dark:bg-rose-950/40 border-rose-200 dark:border-rose-800 text-rose-800 dark:text-rose-200'
                    }`}
                  >
                    <div className="font-semibold mb-1">
                      {sandboxResult.success ? 'Action Executed Successfully' : 'Guardrail Validation Error'}
                    </div>
                    <div>{sandboxResult.message}</div>
                  </div>

                  {sandboxResult.guardrailViolations && (
                    <div className="space-y-1">
                      <span className="text-xs font-semibold text-rose-600">Violations:</span>
                      <ul className="list-disc pl-4 text-xs text-rose-500 space-y-0.5">
                        {sandboxResult.guardrailViolations.map((v: string, idx: number) => (
                          <li key={idx}>{v}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  <div className="space-y-1">
                    <span className="text-xs text-slate-400 font-mono">Response Payload:</span>
                    <pre className="p-3 bg-slate-900 rounded-lg text-xs font-mono text-slate-300 overflow-x-auto max-h-48">
                      {JSON.stringify(sandboxResult, null, 2)}
                    </pre>
                  </div>
                </div>
              ) : (
                <div className="p-12 text-center text-slate-400 text-xs">
                  <Terminal className="w-8 h-8 mx-auto mb-2 text-slate-300 dark:text-slate-600" />
                  Select an action and click <strong>Execute Action</strong> to test server-side mutation guardrails.
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Subtab 4: Advisory Diagnostic Preview */}
      {activeSubTab === 'advisor' && (
        <div className="space-y-6">
          <div className="bg-white dark:bg-slate-800 p-5 rounded-xl border border-slate-200 dark:border-slate-700 shadow-xs space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
              <div>
                <h3 className="font-bold text-base text-slate-900 dark:text-white flex items-center space-x-2">
                  <Sparkles className="w-4 h-4 text-indigo-500" />
                  <span>Personal Study Advisor Review & Action Proposals</span>
                </h3>
                <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                  Demonstrates how the AI evaluates the 9 context domains to formulate action proposals.
                </p>
              </div>

              <button
                onClick={handleSimulateAdvisor}
                className="flex items-center space-x-2 px-3 py-1.5 rounded-lg text-xs font-semibold bg-indigo-600 hover:bg-indigo-500 text-white transition shadow-xs self-start sm:self-auto"
              >
                <RefreshCw className="w-3.5 h-3.5" />
                <span>Re-Analyze Context</span>
              </button>
            </div>

            {advisorRec ? (
              <div className="space-y-4">
                {/* Advisor Analysis Box */}
                <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 space-y-2">
                  <div className="flex items-center justify-between text-xs">
                    <span className="font-semibold text-slate-700 dark:text-slate-300">
                      Advisor Analysis Note:
                    </span>
                    <span className="px-2 py-0.5 rounded bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300 font-mono text-xs">
                      Urgency: {advisorRec.urgencyLevel.toUpperCase()}
                    </span>
                  </div>
                  <p className="text-sm text-slate-800 dark:text-slate-200 leading-relaxed whitespace-pre-line">
                    {advisorRec.advisorAnalysis}
                  </p>
                </div>

                {/* Proposed Actions */}
                <div className="space-y-3">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
                    Recommended Controlled Actions ({advisorRec.suggestedActions.length})
                  </h4>

                  <div className="space-y-2.5">
                    {advisorRec.suggestedActions.map((action, idx) => (
                      <div
                        key={idx}
                        className="p-4 bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 flex flex-col sm:flex-row sm:items-center justify-between gap-3 shadow-xs"
                      >
                        <div className="space-y-1">
                          <div className="flex items-center space-x-2">
                            <span className="text-xs font-bold font-mono px-2 py-0.5 rounded bg-indigo-50 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-800">
                              {action.actionName}
                            </span>
                            <span className="text-sm font-semibold text-slate-900 dark:text-white">
                              {action.description}
                            </span>
                          </div>
                          <pre className="text-xs font-mono text-slate-500 dark:text-slate-400 bg-slate-50 dark:bg-slate-900 p-2 rounded max-h-24 overflow-y-auto">
                            {JSON.stringify(action.parameters, null, 2)}
                          </pre>
                        </div>

                        <button
                          onClick={() => handleExecuteSuggestedAction(action)}
                          disabled={isExecuting}
                          className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-emerald-600 hover:bg-emerald-500 text-white transition self-end sm:self-center"
                        >
                          <CheckCircle2 className="w-3.5 h-3.5" />
                          <span>Approve & Execute</span>
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            ) : (
              <div className="p-8 text-center text-slate-400">
                <Sparkles className="w-8 h-8 mx-auto mb-2 text-indigo-400" />
                <p className="text-sm">Click "Generate Advisor Diagnosis" above to simulate AI recommendations.</p>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Subtab 5: Action Audit Trail */}
      {activeSubTab === 'audit' && (
        <div className="space-y-4">
          <div className="bg-white dark:bg-slate-800 p-4 rounded-xl border border-slate-200 dark:border-slate-700">
            <h3 className="font-bold text-sm text-slate-900 dark:text-white">
              Server-Side Controlled Action Audit Trail
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
              Every mutation triggered by the AI or user passes through the server registry and is immutably logged for safety and traceability.
            </p>
          </div>

          <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 shadow-xs divide-y divide-slate-100 dark:divide-slate-700">
            {auditLogs.map((log) => (
              <div key={log.id} className="p-4 space-y-1.5">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-2">
                    <span className="font-mono text-xs font-bold px-2 py-0.5 rounded bg-slate-100 dark:bg-slate-700 text-slate-800 dark:text-slate-200">
                      {log.actionName}
                    </span>
                    <span
                      className={`text-xs px-2 py-0.5 rounded font-medium ${
                        log.status === 'success'
                          ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300'
                          : 'bg-rose-100 text-rose-800 dark:bg-rose-950 dark:text-rose-300'
                      }`}
                    >
                      {log.status.toUpperCase()}
                    </span>
                  </div>
                  <span className="text-xs font-mono text-slate-400">
                    {new Date(log.timestamp).toLocaleTimeString()}
                  </span>
                </div>
                <p className="text-xs text-slate-700 dark:text-slate-300 font-medium">
                  {log.message}
                </p>
                <div className="text-xs font-mono text-slate-400 bg-slate-50 dark:bg-slate-900 p-2 rounded">
                  Parameters: {JSON.stringify(log.parameters)}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
